#!/bin/bash

# Tell git who I am.
git config --global user.name w0rp
git config --global user.email devw0rp@gmail.com

# Let git figure out branch names for push by default.
git config --global push.default current

# Make `git pull` use --rebase by default.
git config --global pull.rebase true

# Make `git merge` use --no-ff by default
git config --global --add merge.ff false

# Default `git merge` by itself to merging upstream to the branch.
git config --global merge.defaultToUpstream true

# Make git use "patience diff" by default for everything.
git config --global diff.algorithm patience

# Make git use Vim for commit messages, etc.
git config --global core.editor vim

# Disable `git gui` warnings for loose objects.
git config --global gui.gcwarning false

# Set settings for diff-so-fancy
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global color.ui true

git config --global color.diff-highlight.oldNormal    "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal    "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta       "yellow"
git config --global color.diff.frag       "magenta bold"
git config --global color.diff.commit     "yellow bold"
git config --global color.diff.old        "red bold"
git config --global color.diff.new        "green bold"
git config --global color.diff.whitespace "red reverse"
