#!/bin/bash

# Tell git who I am.
git config --global user.name w0rp
git config --global user.email devw0rp@gmail.com

# Let git figure out branch names for push by default.
git config --global push.default current

# Make `git pull` use --rebase by default.
git config --global pull.rebase true

# Make `git merge` use --no-ff by default
git config --global --add merge.ff false

# Default `git merge` by itself to merging upstream to the branch.
git config --global merge.defaultToUpstream true

# Make git use "patience diff" by default for everything.
git config --global diff.algorithm patience

# Make git use Vim for commit messages, etc.
git config --global core.editor vim
