#!/bin/bash

# Aliases for typing git commands really quickly.
alias gd='git diff -M -D --cached'
alias gd_='git diff -M -D'
alias ga='git add -A'
alias justdoit='git add -A :/ && gd'
alias gf='git fetch --all --prune'
alias amend='git commit --amend --no-edit'
alias st='git status'
alias com='git commit -m'
alias gco='git checkout'
# My custom command for deleting everything.
alias gw='git-wipeout'
alias nopyc=$'find `git rev-parse --show-toplevel` -name \'*.pyc\' -not -path \'*/site-packages/*\' -delete'
alias tracking=$'git for-each-ref --format=\'%(upstream:short)\' $(git symbolic-ref -q HEAD)'

# Find branches which have been merge to the dev branch.
alias merged-to-dev=$'git branch --merged dev | cut -c 3- | grep -P --invert-match \'^(?:master|dev|release/.+)$\''

. ~/script/git-completion.bash

# Use git checkout aliases for gco
__git_complete gco _git_checkout

# Make GVim open files in a tab instead of a window.
alias gvim='/usr/bin/gvim --remote-tab-silent'

# Add aliases for the OpenSSL commands I can never remember.
alias check-cert='openssl x509 -text -noout -in'

# Add aliases for messing with strings.
alias udec='python3 -c "import sys, urllib.parse; print(urllib.parse.unquote_plus(\" \".join(sys.argv[1:])))"'
alias uenc='python3 -c "import sys, urllib.parse; print(urllib.parse.quote_plus(\" \".join(sys.argv[1:])))"'

# Brief stat output.
alias bstat='stat --format="%n %U:%G %a" --'

# Make `..` do `cd ..`
alias ..='cd ..'

# Add an alias for re-running hourly cron jobs.
alias rerun-hourly='crontab -l | grep ^@hourly | cut -f 2- -d " " | while read command; do eval $command; done'

