#!/usr/bin/env bash

set -eu

# Update coin market data if it's 10 minutes old.
if ! find ~/.coin-market-data.csv -mmin -10 2> /dev/null | grep -q .; then
    (
        cd ~/git/w0rp-crypto-market-csv
        ./get-csv.sh > ~/.coin-market-data.csv.tmp

        if [[ -s ~/.coin-market-data.csv.tmp ]]; then
            mv ~/.coin-market-data.csv.tmp ~/.coin-market-data.csv
        else
            rm ~/.coin-market-data.csv.tmp
        fi
    )
fi

xdg-open ~/Banking.ods
