#!/usr/bin/env bash

set -eu

# Update coin market data if it's 10 minutes old.
if ! find ~/.coin-market-data.csv -mmin -10 2> /dev/null | grep -q .; then
    (
        cd ~/git/w0rp-crypto-market-csv
        ./get-csv.sh > ~/.coin-market-data.csv
    )
fi

xdg-open ~/Banking.ods
