#!/usr/bin/env bash

set -eu

if [ "$(hostname)" = 'tabby' ]; then
    echo 'Never run this script on Tabby!' 1>&2
    exit 1
fi

options=''
no_root_option=''
no_system_backup=0

while [ $# -ne 0 ]; do
    case $1 in
    --delete)
        options="$options --delete"
        shift
    ;;
    -v)
        options="$options -v"
        shift
    ;;
    --bwlimit=*)
        options="$options $1"
        shift
    ;;
    --no-root)
        no_root_option='--no-root'
        shift
    ;;
    --no-system-backup)
        no_system_backup=1
        shift
    ;;
    --)
        shift
        break
    ;;
    -?*)
        echo "Invalid argument: $1" 1>&2
        exit 1
    ;;
    *)
        break
    ;;
    esac
done

if ! ssh -q tabby 'exit'; then
    echo 'tabby cannot be reached!' 1>&2
    exit 1
fi

mkdir -p ~/.backup/

if ! ((no_system_backup)); then
    # Set up tabby to mount desktop directories.
    ssh tabby 'ping -c1 -W1 desktop &>/dev/null && (mountpoint /desktop &>/dev/null || sshfs -o allow_root,reconnect,ServerAliveInterval=5,ServerAliveCountMax=3 desktop:/home/w0rp/ /desktop/); ping -c1 -W1 desktop &>/dev/null && (mountpoint /desktop-content &>/dev/null || sshfs -o allow_root,reconnect,ServerAliveInterval=5,ServerAliveCountMax=3 desktop:/content /desktop-content/)'

    echo 'Backing up Tabby ...' 1>&2

    # shellcheck disable=SC2086
    # Run the backup script on Tabby, back to this machine.
    ssh -t tabby ~/script/linux/backup-system $options $no_root_option \
        /desktop-content/.tabby-backup/
fi

echo 'rsyncing tabby ~/phone_backup/DCIM' 1>&2

# shellcheck disable=SC2086
rsync -au --info=flist0,stats0 $options \
    tabby:~/phone_backup/DCIM/ /content/image/DCIM/

echo 'rsyncing tabby /content' 1>&2

# shellcheck disable=SC2086
rsync -au --info=flist0,stats0 $options \
    --include='/audio/' \
    --include='/audio/music/' \
    --include='/audio/music/**' \
    --exclude='*' \
    tabby:~/content/ /content/

# Use rsync to find differences by using a verbose dry run.
rsync --dry-run -v --info=flist0,stats0 -rl --ignore-existing \
    /content/image/DCIM/ tabby:~/phone_backup/DCIM/ \
    > ~/.backup/tabby_dcim_missing

rsync --dry-run -v --info=flist0,stats0 -rl --ignore-existing \
    --include='/audio/' \
    --include='/audio/music/' \
    --include='/audio/music/**' \
    --exclude='*' \
    /content/ tabby:~/content/ > ~/.backup/tabby_missing

if [ -s "$HOME/.backup/tabby_dcim_missing" ]; then
    echo "Some files have been removed from DCIM." 1>&2
    echo "Check ~/.backup/tabby_dcim_missing" 1>&2
fi

if [ -s "$HOME/.backup/tabby_missing" ]; then
    echo "Some files have been removed from Tabby." 1>&2
    echo "Check ~/.backup/tabby_missing" 1>&2
fi
