#!/bin/bash -eu

# This script runs stubgen to produce an 'out' directory, and then rsyncs the
# new stubs into the 'stubs' directory, so they can be used.

if [ $# -eq 0 ]; then
    echo 'No arguments given' 1>&2
    exit 1
fi

if [ -d out ]; then
    find out \( -name '*.py' -o -name '*.pyi' \) -delete
    rmdir out
fi

# The sed expressions will...
#
# Automatically remove site-packages directories from paths.
# Remove :: method syntax from paths.
# Remove .py files from the ends of paths.
# Turn slashes into dots for module paths.
corrected_path=$(echo "$1" | sed 's/^.*site-packages\///' | sed 's/::.*$//' | sed 's/\.py$//' | sed 's:/:.:g')

mkdir out
stubgen "$corrected_path"

rsync -auv out/ stubs/
rm -r out
