#!/usr/bin/env python

"""
Given some JSON via stdin, write multi-line JSON to stdout ready for pasting
into Vim.
"""

import json
import sys


def main():
    obj = json.load(sys.stdin)
    json_lines = json.dumps(obj, indent=2, sort_keys=True).split('\n')

    for index, line in enumerate(json_lines):
        if index == 0:
            sys.stdout.write(line)
        else:
            sys.stdout.write('\\')

            if index == len(json_lines) - 1:
                sys.stdout.write(line)
            else:
                sys.stdout.write(line[1:])

        sys.stdout.write('\n')


if __name__ == "__main__":
    main()
