#!/bin/bash

# w0rp's script for backing up his shit.
# Public domain.

command -v rsync > /dev/null 2>&1 || {
    echo 'rsync is not installed! Aborting.' 1>&2
    exit 1
}

if [ -z "$1" ]; then
    echo 'Please supply a directory to copy home contents to.' 1>&2
    exit 1
fi

if [ ! -d "$1"  ]; then
    echo 'The given output path is not a directory.' 1>&2
    exit 1
fi

list=(
    .mozilla
    .thunderbird
    .pekwm
    .config
    .fonts
    .gtkrc-2.0
    .gtk-bookmarks
    .xscreensaver
    .purple
    .themes
    .imwheelrc
    content
    saves
)

echo "Backing up HOME to: $1" 1>&2

for item in ${list[@]}; do
    src="$HOME/$item"
    dst="$1/$item"

    if [ -f "$src" ]; then
        # This also copies symlinks.
        echo "cp: $item"
        cp -a "$src" "$dst"
    elif [ -d "$src" ]; then
        if [ ! -d "$dst" ]; then
            mkdir "$dst"
        fi

        echo "rsync: $item"
        rsync -rltzu --delete "$src/" "$dst"
    else
        echo ‘"$src"'‘ does not exist!' 1>&2
    fi
done

