#!/bin/bash -eu

# Run a command in the background without hangups, and without output,
# unless explicitly asked for.

if test -t 1; then
    exec 1> /dev/null
fi

if test -t 2; then
    exec 2> /dev/null
fi

"$@" &
