#!/bin/bash -eu

user=`whoami`
rsync="rsync -rltzuv --info=flist0,stats0 --chown=$user:$user"

service_exists() {
    service --status-all 2> /dev/null | grep ' '"$1"'$' > /dev/null
}

while [ $# -ne 0 ]; do
    case $1 in
    --delete)
        rsync="$rsync --delete"
        shift
    ;;
    --)
        shift
        break
    ;;
    -?*)
        echo "Invalid argument: $1" 1>&2
        exit 1
    ;;
    *)
        break
    ;;
    esac
done

if [ $# -eq 0 ] || [ -z "$1" ]; then
    echo "Please provide a destination directory." 1>&2
    exit 1
fi

dest_dir="$1"

if [ ! -d "$dest_dir" ]; then
    echo "$dest_dir does not exist!" 1>&2
    exit 1
fi

if [ "$dest_dir" == '/' ]; then
    echo "/ cannot be used as a destination directory!" 1>&2
    exit 1
fi

backup_root_dirs() {
    # rsync some parts of /etc/
    echo 'Backing up /etc/' 1>&2
    mkdir -p "$dest_dir/etc/"
    chown $user:$user "$dest_dir/etc/"
    $rsync \
        --include='/' \
        --include='/etc/' \
        --include='/etc/ssh/' \
        --include='/etc/ssh/sshd_config' \
        --include='/etc/apt/' \
        --include='/etc/apt/sources.list.d/' \
        --include='/etc/apt/sources.list.d/*' \
        --include='/etc/samba/' \
        --include='/etc/samba/*' \
        --include='/etc/postgresql/' \
        --include='/etc/postgresql/**' \
        --include='/var/' \
        --include='/var/lib/' \
        --include='/var/lib/postgresql/' \
        --include='/var/lib/postgresql/**' \
        --exclude='*' \
        / "$dest_dir/"

    # If Postgres is installed, rsync it again quickly while it's offline.
    if service_exists postgresql; then
        echo 'Making final postgres backup' 1>&2
        service postgresql stop
        $rsync \
            --include='/var/' \
            --include='/var/lib/' \
            --include='/var/lib/postgresql/' \
            --include='/var/lib/postgresql/**' \
            --exclude='*' \
        / "$dest_dir/"
        service postgresql start
    fi
}

# Run the root backup commands as root with one sudo invocation.
sudo bash -euc "user='$user'; dest_dir='$dest_dir'; rsync='$rsync'; $(declare -f service_exists); $(declare -f backup_root_dirs); backup_root_dirs"

# rsync the /home/ directory.
echo 'Backing up /home/' 1>&2
mkdir -p "$dest_dir/home/$user/"
$rsync \
    --exclude-from="$HOME/.rsync_excludes" \
    --exclude='/.crontab' \
    ~/ "$dest_dir/home/$user/"

# Output the full list of packages installed through apt.
apt-mark showmanual > "$dest_dir/apt-packages"
# Output crontab to the destination directory.
crontab -l > "$dest_dir/home/$user/.crontab"
