#!/bin/bash -eu

# Brief, but human readable, stat output.

for filename in "$@"; do
    size=$(numfmt --to=iec --suffix=B --format="%f" $(stat -c %s -- "$filename"))
    stat --format="%U:%G:%a %n [$size]" -- "$filename"
done
