#!/bin/bash -eu

# A script for finding all music in a list of files and directories,
# and presenting it in a natural-sorted order.

if [ $# -eq 0 ]; then
    echo 'Please provide at least one file or directory!' 1>&2
    exit 1
fi

files=()

for arg in "$@"; do
    files+=("$(readlink -f -- "$arg")")
done

find "${files[@]}" -type f \
    \( \
        -iname '*.mp3' \
        -o -iname '*.m4a' \
        -o -iname '*.flac' \
        -o -iname '*.wav' \
        -o -iname '*.aac' \
        -o -iname '*.sid' \
        -o -iname '*.spc' \
    \) \
    | sort -V
