#!/bin/bash -eu

# A script for finding all music in a directory, and presenting it in a
# natural-sorted order.

if [ $# -eq 0 ] || [ -z "$1" ]; then
    echo 'Please provide a directory!' 1>&2
    exit 1
fi

find "$1" -type f \
    \( \
        -iname '*.mp3' \
        -o -iname '*.m4a' \
        -o -iname '*.flac' \
        -o -iname '*.wav' \
        -o -iname '*.aac' \
        -o -iname '*.sid' \
        -o -iname '*.spc' \
    \) \
    | sort -V
