#!/bin/bash -eu

cached=''

while [ $# -ne 0 ]; do
    case $1 in
    --cached)
        cached='--cached'
        shift
    ;;
    --)
        shift
        break
    ;;
    -?*)
        echo "Invalid argument: $1" 1>&2
        exit 1
    ;;
    *)
        break
    ;;
    esac
done

dir="$(pwd)"

# Walk up parent paths until we git the git directory.
while [ ! -d  '.git/objects' ] && [ "$PWD" != / ]; do
    cd ..
done

if [ ! -d  '.git/objects' ]; then
    echo 'This is not a git repository directory.' 1>&2
    exit 1
fi

if [ -f '.gitmodules' ]; then
    # Look through git modules.
    # If the directory we were originally in was inside of a git submodule,
    # Then we should change directories to the root of the submodule.
    for path in $(grep -Po '(?<=path = ).*' .gitmodules ); do
        mod="$(pwd)/$path"

        if [ "${dir:0:${#mod}}" == "$mod" ]; then
            cd "$mod"
            break
        fi
    done
fi

function escape-slashes() {
    echo "$1" | sed -r 's/\\\//\//g' | sed -r 's/\//\\\//g'
}

git_root="$(pwd)"

if [ $# -ne 0 ]; then
    git diff --name-only $cached "$1" | uniq | sed -e "s/^/$(escape-slashes "$git_root")\\//"
else
    git diff --name-only $cached | uniq | sed -e "s/^/$(escape-slashes "$git_root")\\//"
fi
