#!/bin/bash

set -e

# Walk up parent paths until we git the git directory.
while [ ! -d  '.git/objects' ] && [ "$PWD" != / ]; do
    cd ..
done

if [ ! -d  '.git/objects' ]; then
    echo 'This is not a git repository directory.' 1>&2
    exit 1
fi

function escape-slashes() {
    echo $1 | sed -r 's/\\\//\//g' | sed -r 's/\//\\\//g'
}

git_root=`pwd`

git diff --name-only "$1" | uniq | sed -e "s/^/$(escape-slashes "$git_root")\\//"
