#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo 'Usage: mkenv <dirname> [<python_interpreter>]' 1>&2
    exit 1
fi

env_dir="$1"

# Set the interpreter to use, defaulting to just 'python'
if [ -n "$2" ]; then
    python="$2"
else
    python='python'
fi

if [ ! -d ~/.pip-packages ]; then
    mkdir ~/.pip-packages
fi

creating=0

if [ ! -f "$env_dir"/bin/activate ]; then
    creating=1
fi

if (( creating )); then
    virtualenv --no-site-packages -p "$python" "$env_dir"
fi

source "$env_dir"/bin/activate

if (( creating )); then
    easy_install -U pip
fi

pip install -r requirements.txt

