#!/bin/bash -eu

# This script makes it easy to record audio from M-Audio devices using only
# ALSA and command line tools.

if ! command -v flac &> /dev/null; then
    echo 'Please install flac first!' 1>&2
    exit 1
fi

dir="$HOME/content/audio/recordings"
filename="$(date '+%Y-%m-%d %H-%M-%S').flac"
device="$(
    arecord -l \
    | grep 'M2X2M.*device 0' \
    | sed 's/^card \([0-9][0-9]*\):.*/\1/'
)"

if [ -z "$device" ]; then
    echo $'Couldn\'t find the audio device!' 1>&2
    echo $'Check your connection and arecord -l' 1>&2
    exit 1
fi

mkdir -p "$dir"

echo 'Recording audio...'
# The M-Audio device outputs 32-bit little endian, at 44,100Hz, on channel 2,
# trapping SIGINT for only arecord.
trap -- '' SIGINT
arecord --device=hw:"$device" -f S32_LE -r44100 -c 2 "$dir/output-32bit.wav" || true
trap - SIGINT
trap

echo 'Converting from 32-bit PCM to 16-bit PCM...'
# We want 16-bit PCM for playback.
ffmpeg -loglevel error -y -i "$dir/output-32bit.wav" -acodec pcm_s16le \
    "$dir/output-16bit-lowvolume.wav"

# Increase the volume on the recordings, as they are very quiet.
echo 'Increasing volume of recording...'
ffmpeg -loglevel error -y -i "$dir/output-16bit-lowvolume.wav" \
    -af "volume=16.0" "$dir/output-16bit.wav"

echo 'Converting to FLAC...'
flac -s --best -f -o "$dir/$filename" "$dir/output-16bit.wav"

rm "$dir/output-32bit.wav"
rm "$dir/output-16bit-lowvolume.wav"
rm "$dir/output-16bit.wav"

echo
echo
echo "Your recording is now available as $filename"
