#!/usr/bin/env python

"""
A Python script for converting a .torrent file to a magnet link.

Python 2 is required for this script, as is the bencode module.
"""

import base64
import hashlib
import sys
from urllib import urlencode

import bencode


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: torrent-to-magnet <torrent_filename>")

    with open(sys.argv[1]) as torrent_file:
        torrent_data = torrent_file.read()

    metadata = bencode.bdecode(torrent_data)
    info_data = bencode.bencode(metadata["info"])
    magnet_hash = base64.b32encode(hashlib.sha1(info_data).digest())

    querystring = urlencode([
        ("dn", metadata["info"]["name"]),
        ("tr", metadata["announce"]),
    ])

    print("magnet:?xt=urn:btih:{}&{}".format(magnet_hash, querystring))

if __name__ == "__main__":
    main()
