#!/usr/bin/env python

"""
A Python script for converting a .torrent file to a magnet link.

python-libtorrent is required for this script.
"""

import sys
from urllib import urlencode

import libtorrent


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: torrent-to-magnet <torrent_filename>")

    session = libtorrent.session()  # noqa
    info = libtorrent.torrent_info(sys.argv[1])

    params = [
        ("dn", info.name()),
    ]
    params.extend(("tr", tr.url) for tr in info.trackers())

    print("magnet:?xt=urn:btih:{}&{}".format(
        info.info_hash(),
        urlencode(params),
    ))

if __name__ == "__main__":
    main()
