#!/usr/bin/env python3

"""
A Python script for turning all arguments into a URL-encoded string.
"""

import sys
import urllib.parse


def main():
    text = " ".join(sys.argv[1:])

    print(urllib.parse.quote(text))

if __name__ == "__main__":
    main()
