#!/usr/bin/env python

import sys
import subprocess
import getopt

if __name__ == "__main__":
    opt_list, arg_list = getopt.getopt(sys.argv[1:], "", ["clear", "play"])

    opt_dict = dict(opt_list)

    # Always load files in a sorted order.
    arg_list.sort()

    if "--clear" in opt_dict:
        subprocess.call(("xmms2", "clear"))

    for arg in arg_list:
        print(arg)

        subprocess.call(("xmms2", "add", arg))

    if "--play" in opt_dict:
        subprocess.call(("xmms2", "play"))
