#!/bin/bash -eu

if [ $# -eq 0 ] || [ -z "$1" ]; then
    echo 'Please provide at least one file or directory!' 1>&2
    exit 1
fi

~/script/linux/find-music "$@" | {
    files=()

    while read line; do
        files+=("$line")
    done

    xmms2 add "${files[@]}"
}
