#!/bin/bash -eu

if [ $# -eq 0 ] || [ -z "$1" ]; then
    echo 'Please provide at least one file or directory!' 1>&2
    exit 1
fi

# Stop current music and clear all items.
xmms2 stop
xmms2 remove '*'
# Add the items and hit play
~/script/linux/xmms2-add-all "$@"
xmms2 play
