#!/usr/bin/env bash

# This script is used by my 've' alias for activating virtualenv easily by
# detecting where the script is. This only works for Bash, and won't screw up
# other settings in the terminal like aliases.

for dir in ve env; do
    if [ -d "$dir" ]; then
        base_virtual_env_dir="$dir"
        break
    fi
done

if [ -n "$base_virtual_env_dir" ] ; then
    deactivate () {
        unset VIRTUAL_ENV

        if [ -n "$_OLD_VIRTUAL_PATH" ] ; then
            PATH="$_OLD_VIRTUAL_PATH"
            export PATH
            unset _OLD_VIRTUAL_PATH
        fi

        if [ -n "$_OLD_VIRTUAL_PYTHONHOME" ] ; then
            PYTHONHOME="$_OLD_VIRTUAL_PYTHONHOME"
            export PYTHONHOME
            unset _OLD_VIRTUAL_PYTHONHOME
        fi

        if [ -n "$_OLD_VIRTUAL_PS1" ] ; then
            PS1="$_OLD_VIRTUAL_PS1"
            export PS1
            unset _OLD_VIRTUAL_PS1
        fi

        if [ -n "$_OLD_VIRTUAL_DJANGO_SETTINGS_MODULE" ] ; then
            DJANGO_SETTINGS_MODULE="$_OLD_VIRTUAL_DJANGO_SETTINGS_MODULE"
            export DJANGO_SETTINGS_MODULE
            unset _OLD_VIRTUAL_DJANGO_SETTINGS_MODULE
        fi

        if [ ! "$1" = "nondestructive" ] ; then
            unset -f deactivate
        fi
    }

    deactivate nondestructive

    VIRTUAL_ENV="$PWD/$base_virtual_env_dir"
    export VIRTUAL_ENV

    _OLD_VIRTUAL_PATH="$PATH"
    PATH="$VIRTUAL_ENV/bin:$PATH"
    export PATH

    if [ -n "$PYTHONHOME" ] ; then
        _OLD_VIRTUAL_PYTHONHOME="$PYTHONHOME"
        unset PYTHONHOME
    fi

    _OLD_VIRTUAL_PS1="$PS1"
    PS1="($base_virtual_env_dir)$PS1"
    export PS1

    # Detect Django settings modules, and use them.
    if [ -f spotlight/settings/w0rp.py ]; then
        _OLD_VIRTUAL_DJANGO_SETTINGS_MODULE="$DJANGO_SETTINGS_MODULE"
        DJANGO_SETTINGS_MODULE="spotlight.settings.w0rp"
        export DJANGO_SETTINGS_MODULE
    fi

    if [ -f api_proj/settings/dev.py ]; then
        _OLD_VIRTUAL_DJANGO_SETTINGS_MODULE="$DJANGO_SETTINGS_MODULE"
        DJANGO_SETTINGS_MODULE="spotlight.settings.w0rp_api"
        export DJANGO_SETTINGS_MODULE
    fi

    if [ -f cloud_proxy/settings/dev.py ]; then
        _OLD_VIRTUAL_DJANGO_SETTINGS_MODULE="$DJANGO_SETTINGS_MODULE"
        DJANGO_SETTINGS_MODULE="cloud_proxy.settings.w0rp"
        export DJANGO_SETTINGS_MODULE
    fi
else
    echo 'The virtualenv dir could not be detected' 1>&2
fi
